apiVersion: v1
kind: Pod
metadata:
  name: chunkuploader
  namespace: esd
spec:
  containers:
  - name: chunkuploader-container
    image: harbor.eencloud.com/test/chunkuploader:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
